### ISSUE TITLE
Practica De Mockup

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/practica-de-mockup-y-front-end-tecnopower#2]
[Practica de 3 de Mockup.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-mockup-y-front-end-tecnopower/files/8444541/Practica.de.3.de.Mockup.pdf)

**Comment by IsraelNicolas61** [comment]
19% de 20%

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/163260081-7acf7caa-8e3d-4048-b6a9-ae4d68c4f507.png)
Para el diseño de una Dapp y para asegurar la seguridad con Near no es necesario capturar el usuario y contraseña

**Comment by josealfredo79** [comment]
![image](https://user-images.githubusercontent.com/58342642/163260789-6288412e-a2d9-4d12-9a57-fadd3d3e58fc.png)
Se debe realizar el logis con inicio sesion de login para una mayor seguridad y que sea descentralizado
Aquí el ejemplo https://learnnear.club/

**Comment by josealfredo79** [comment]
Favor de modificar para tomar en cuenta la practica...
